<?php
/**
 * ChannelsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  emailguardSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EmailGuard Public API
 *
 * Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dev@emailguard.co
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace emailguardSdk\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use emailguardSdk\ApiException;
use emailguardSdk\Configuration;
use emailguardSdk\FormDataProcessor;
use emailguardSdk\HeaderSelector;
use emailguardSdk\ObjectSerializer;

/**
 * ChannelsApi Class Doc Comment
 *
 * @category Class
 * @package  emailguardSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ChannelsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'apiV1TeamNotificationsChannelsChannelIdDelete' => [
            'application/json',
        ],
        'apiV1TeamNotificationsChannelsChannelIdPut' => [
            'application/json',
        ],
        'apiV1TeamNotificationsChannelsChannelIdTestPost' => [
            'application/json',
        ],
        'apiV1TeamNotificationsChannelsGet' => [
            'application/json',
        ],
        'apiV1TeamNotificationsChannelsPost' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation apiV1TeamNotificationsChannelsChannelIdDelete
     *
     * Delete notification channel
     *
     * @param  string $channel_id UUID of the notification channel to delete (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsChannelsChannelIdDelete'] to see the possible values for this operation
     *
     * @throws \emailguardSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \emailguardSdk\Model\MessageResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse
     */
    public function apiV1TeamNotificationsChannelsChannelIdDelete($channel_id, string $contentType = self::contentTypes['apiV1TeamNotificationsChannelsChannelIdDelete'][0])
    {
        list($response) = $this->apiV1TeamNotificationsChannelsChannelIdDeleteWithHttpInfo($channel_id, $contentType);
        return $response;
    }

    /**
     * Operation apiV1TeamNotificationsChannelsChannelIdDeleteWithHttpInfo
     *
     * Delete notification channel
     *
     * @param  string $channel_id UUID of the notification channel to delete (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsChannelsChannelIdDelete'] to see the possible values for this operation
     *
     * @throws \emailguardSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \emailguardSdk\Model\MessageResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1TeamNotificationsChannelsChannelIdDeleteWithHttpInfo($channel_id, string $contentType = self::contentTypes['apiV1TeamNotificationsChannelsChannelIdDelete'][0])
    {
        $request = $this->apiV1TeamNotificationsChannelsChannelIdDeleteRequest($channel_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\MessageResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\emailguardSdk\Model\MessageResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\MessageResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV1TeamNotificationsChannelsChannelIdDeleteAsync
     *
     * Delete notification channel
     *
     * @param  string $channel_id UUID of the notification channel to delete (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsChannelsChannelIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1TeamNotificationsChannelsChannelIdDeleteAsync($channel_id, string $contentType = self::contentTypes['apiV1TeamNotificationsChannelsChannelIdDelete'][0])
    {
        return $this->apiV1TeamNotificationsChannelsChannelIdDeleteAsyncWithHttpInfo($channel_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1TeamNotificationsChannelsChannelIdDeleteAsyncWithHttpInfo
     *
     * Delete notification channel
     *
     * @param  string $channel_id UUID of the notification channel to delete (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsChannelsChannelIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1TeamNotificationsChannelsChannelIdDeleteAsyncWithHttpInfo($channel_id, string $contentType = self::contentTypes['apiV1TeamNotificationsChannelsChannelIdDelete'][0])
    {
        $returnType = '\emailguardSdk\Model\MessageResponse';
        $request = $this->apiV1TeamNotificationsChannelsChannelIdDeleteRequest($channel_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1TeamNotificationsChannelsChannelIdDelete'
     *
     * @param  string $channel_id UUID of the notification channel to delete (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsChannelsChannelIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1TeamNotificationsChannelsChannelIdDeleteRequest($channel_id, string $contentType = self::contentTypes['apiV1TeamNotificationsChannelsChannelIdDelete'][0])
    {

        // verify the required parameter 'channel_id' is set
        if ($channel_id === null || (is_array($channel_id) && count($channel_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $channel_id when calling apiV1TeamNotificationsChannelsChannelIdDelete'
            );
        }


        $resourcePath = '/api/v1/team/notifications/channels/{channelId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($channel_id !== null) {
            $resourcePath = str_replace(
                '{channelId}',
                ObjectSerializer::toPathValue($channel_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1TeamNotificationsChannelsChannelIdPut
     *
     * Update notification channel
     *
     * @param  string $channel_id UUID of the notification channel to update (required)
     * @param  \emailguardSdk\Model\UpdateNotificationChannelInput $update_notification_channel_input Updated channel name and/or configuration (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsChannelsChannelIdPut'] to see the possible values for this operation
     *
     * @throws \emailguardSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \emailguardSdk\Model\GetNotificationChannelResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse
     */
    public function apiV1TeamNotificationsChannelsChannelIdPut($channel_id, $update_notification_channel_input, string $contentType = self::contentTypes['apiV1TeamNotificationsChannelsChannelIdPut'][0])
    {
        list($response) = $this->apiV1TeamNotificationsChannelsChannelIdPutWithHttpInfo($channel_id, $update_notification_channel_input, $contentType);
        return $response;
    }

    /**
     * Operation apiV1TeamNotificationsChannelsChannelIdPutWithHttpInfo
     *
     * Update notification channel
     *
     * @param  string $channel_id UUID of the notification channel to update (required)
     * @param  \emailguardSdk\Model\UpdateNotificationChannelInput $update_notification_channel_input Updated channel name and/or configuration (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsChannelsChannelIdPut'] to see the possible values for this operation
     *
     * @throws \emailguardSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \emailguardSdk\Model\GetNotificationChannelResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1TeamNotificationsChannelsChannelIdPutWithHttpInfo($channel_id, $update_notification_channel_input, string $contentType = self::contentTypes['apiV1TeamNotificationsChannelsChannelIdPut'][0])
    {
        $request = $this->apiV1TeamNotificationsChannelsChannelIdPutRequest($channel_id, $update_notification_channel_input, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\GetNotificationChannelResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\emailguardSdk\Model\GetNotificationChannelResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\GetNotificationChannelResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV1TeamNotificationsChannelsChannelIdPutAsync
     *
     * Update notification channel
     *
     * @param  string $channel_id UUID of the notification channel to update (required)
     * @param  \emailguardSdk\Model\UpdateNotificationChannelInput $update_notification_channel_input Updated channel name and/or configuration (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsChannelsChannelIdPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1TeamNotificationsChannelsChannelIdPutAsync($channel_id, $update_notification_channel_input, string $contentType = self::contentTypes['apiV1TeamNotificationsChannelsChannelIdPut'][0])
    {
        return $this->apiV1TeamNotificationsChannelsChannelIdPutAsyncWithHttpInfo($channel_id, $update_notification_channel_input, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1TeamNotificationsChannelsChannelIdPutAsyncWithHttpInfo
     *
     * Update notification channel
     *
     * @param  string $channel_id UUID of the notification channel to update (required)
     * @param  \emailguardSdk\Model\UpdateNotificationChannelInput $update_notification_channel_input Updated channel name and/or configuration (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsChannelsChannelIdPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1TeamNotificationsChannelsChannelIdPutAsyncWithHttpInfo($channel_id, $update_notification_channel_input, string $contentType = self::contentTypes['apiV1TeamNotificationsChannelsChannelIdPut'][0])
    {
        $returnType = '\emailguardSdk\Model\GetNotificationChannelResponse';
        $request = $this->apiV1TeamNotificationsChannelsChannelIdPutRequest($channel_id, $update_notification_channel_input, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1TeamNotificationsChannelsChannelIdPut'
     *
     * @param  string $channel_id UUID of the notification channel to update (required)
     * @param  \emailguardSdk\Model\UpdateNotificationChannelInput $update_notification_channel_input Updated channel name and/or configuration (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsChannelsChannelIdPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1TeamNotificationsChannelsChannelIdPutRequest($channel_id, $update_notification_channel_input, string $contentType = self::contentTypes['apiV1TeamNotificationsChannelsChannelIdPut'][0])
    {

        // verify the required parameter 'channel_id' is set
        if ($channel_id === null || (is_array($channel_id) && count($channel_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $channel_id when calling apiV1TeamNotificationsChannelsChannelIdPut'
            );
        }

        // verify the required parameter 'update_notification_channel_input' is set
        if ($update_notification_channel_input === null || (is_array($update_notification_channel_input) && count($update_notification_channel_input) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $update_notification_channel_input when calling apiV1TeamNotificationsChannelsChannelIdPut'
            );
        }


        $resourcePath = '/api/v1/team/notifications/channels/{channelId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($channel_id !== null) {
            $resourcePath = str_replace(
                '{channelId}',
                ObjectSerializer::toPathValue($channel_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($update_notification_channel_input)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($update_notification_channel_input));
            } else {
                $httpBody = $update_notification_channel_input;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1TeamNotificationsChannelsChannelIdTestPost
     *
     * Test notification channel
     *
     * @param  string $channel_id UUID of the webhook channel to test (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsChannelsChannelIdTestPost'] to see the possible values for this operation
     *
     * @throws \emailguardSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \emailguardSdk\Model\MessageResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse
     */
    public function apiV1TeamNotificationsChannelsChannelIdTestPost($channel_id, string $contentType = self::contentTypes['apiV1TeamNotificationsChannelsChannelIdTestPost'][0])
    {
        list($response) = $this->apiV1TeamNotificationsChannelsChannelIdTestPostWithHttpInfo($channel_id, $contentType);
        return $response;
    }

    /**
     * Operation apiV1TeamNotificationsChannelsChannelIdTestPostWithHttpInfo
     *
     * Test notification channel
     *
     * @param  string $channel_id UUID of the webhook channel to test (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsChannelsChannelIdTestPost'] to see the possible values for this operation
     *
     * @throws \emailguardSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \emailguardSdk\Model\MessageResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1TeamNotificationsChannelsChannelIdTestPostWithHttpInfo($channel_id, string $contentType = self::contentTypes['apiV1TeamNotificationsChannelsChannelIdTestPost'][0])
    {
        $request = $this->apiV1TeamNotificationsChannelsChannelIdTestPostRequest($channel_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\MessageResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\emailguardSdk\Model\MessageResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\MessageResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV1TeamNotificationsChannelsChannelIdTestPostAsync
     *
     * Test notification channel
     *
     * @param  string $channel_id UUID of the webhook channel to test (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsChannelsChannelIdTestPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1TeamNotificationsChannelsChannelIdTestPostAsync($channel_id, string $contentType = self::contentTypes['apiV1TeamNotificationsChannelsChannelIdTestPost'][0])
    {
        return $this->apiV1TeamNotificationsChannelsChannelIdTestPostAsyncWithHttpInfo($channel_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1TeamNotificationsChannelsChannelIdTestPostAsyncWithHttpInfo
     *
     * Test notification channel
     *
     * @param  string $channel_id UUID of the webhook channel to test (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsChannelsChannelIdTestPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1TeamNotificationsChannelsChannelIdTestPostAsyncWithHttpInfo($channel_id, string $contentType = self::contentTypes['apiV1TeamNotificationsChannelsChannelIdTestPost'][0])
    {
        $returnType = '\emailguardSdk\Model\MessageResponse';
        $request = $this->apiV1TeamNotificationsChannelsChannelIdTestPostRequest($channel_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1TeamNotificationsChannelsChannelIdTestPost'
     *
     * @param  string $channel_id UUID of the webhook channel to test (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsChannelsChannelIdTestPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1TeamNotificationsChannelsChannelIdTestPostRequest($channel_id, string $contentType = self::contentTypes['apiV1TeamNotificationsChannelsChannelIdTestPost'][0])
    {

        // verify the required parameter 'channel_id' is set
        if ($channel_id === null || (is_array($channel_id) && count($channel_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $channel_id when calling apiV1TeamNotificationsChannelsChannelIdTestPost'
            );
        }


        $resourcePath = '/api/v1/team/notifications/channels/{channelId}/test';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($channel_id !== null) {
            $resourcePath = str_replace(
                '{channelId}',
                ObjectSerializer::toPathValue($channel_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1TeamNotificationsChannelsGet
     *
     * List notification channels
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsChannelsGet'] to see the possible values for this operation
     *
     * @throws \emailguardSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \emailguardSdk\Model\GetNotificationChannelsResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse
     */
    public function apiV1TeamNotificationsChannelsGet(string $contentType = self::contentTypes['apiV1TeamNotificationsChannelsGet'][0])
    {
        list($response) = $this->apiV1TeamNotificationsChannelsGetWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation apiV1TeamNotificationsChannelsGetWithHttpInfo
     *
     * List notification channels
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsChannelsGet'] to see the possible values for this operation
     *
     * @throws \emailguardSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \emailguardSdk\Model\GetNotificationChannelsResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1TeamNotificationsChannelsGetWithHttpInfo(string $contentType = self::contentTypes['apiV1TeamNotificationsChannelsGet'][0])
    {
        $request = $this->apiV1TeamNotificationsChannelsGetRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\GetNotificationChannelsResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\emailguardSdk\Model\GetNotificationChannelsResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\GetNotificationChannelsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV1TeamNotificationsChannelsGetAsync
     *
     * List notification channels
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsChannelsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1TeamNotificationsChannelsGetAsync(string $contentType = self::contentTypes['apiV1TeamNotificationsChannelsGet'][0])
    {
        return $this->apiV1TeamNotificationsChannelsGetAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1TeamNotificationsChannelsGetAsyncWithHttpInfo
     *
     * List notification channels
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsChannelsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1TeamNotificationsChannelsGetAsyncWithHttpInfo(string $contentType = self::contentTypes['apiV1TeamNotificationsChannelsGet'][0])
    {
        $returnType = '\emailguardSdk\Model\GetNotificationChannelsResponse';
        $request = $this->apiV1TeamNotificationsChannelsGetRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1TeamNotificationsChannelsGet'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsChannelsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1TeamNotificationsChannelsGetRequest(string $contentType = self::contentTypes['apiV1TeamNotificationsChannelsGet'][0])
    {


        $resourcePath = '/api/v1/team/notifications/channels';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1TeamNotificationsChannelsPost
     *
     * Create notification channel
     *
     * @param  \emailguardSdk\Model\CreateNotificationChannelInput $create_notification_channel_input Channel name, type, and type-specific configuration (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsChannelsPost'] to see the possible values for this operation
     *
     * @throws \emailguardSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \emailguardSdk\Model\GetNotificationChannelResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse
     */
    public function apiV1TeamNotificationsChannelsPost($create_notification_channel_input, string $contentType = self::contentTypes['apiV1TeamNotificationsChannelsPost'][0])
    {
        list($response) = $this->apiV1TeamNotificationsChannelsPostWithHttpInfo($create_notification_channel_input, $contentType);
        return $response;
    }

    /**
     * Operation apiV1TeamNotificationsChannelsPostWithHttpInfo
     *
     * Create notification channel
     *
     * @param  \emailguardSdk\Model\CreateNotificationChannelInput $create_notification_channel_input Channel name, type, and type-specific configuration (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsChannelsPost'] to see the possible values for this operation
     *
     * @throws \emailguardSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \emailguardSdk\Model\GetNotificationChannelResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1TeamNotificationsChannelsPostWithHttpInfo($create_notification_channel_input, string $contentType = self::contentTypes['apiV1TeamNotificationsChannelsPost'][0])
    {
        $request = $this->apiV1TeamNotificationsChannelsPostRequest($create_notification_channel_input, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\GetNotificationChannelResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\emailguardSdk\Model\GetNotificationChannelResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\GetNotificationChannelResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV1TeamNotificationsChannelsPostAsync
     *
     * Create notification channel
     *
     * @param  \emailguardSdk\Model\CreateNotificationChannelInput $create_notification_channel_input Channel name, type, and type-specific configuration (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsChannelsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1TeamNotificationsChannelsPostAsync($create_notification_channel_input, string $contentType = self::contentTypes['apiV1TeamNotificationsChannelsPost'][0])
    {
        return $this->apiV1TeamNotificationsChannelsPostAsyncWithHttpInfo($create_notification_channel_input, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1TeamNotificationsChannelsPostAsyncWithHttpInfo
     *
     * Create notification channel
     *
     * @param  \emailguardSdk\Model\CreateNotificationChannelInput $create_notification_channel_input Channel name, type, and type-specific configuration (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsChannelsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1TeamNotificationsChannelsPostAsyncWithHttpInfo($create_notification_channel_input, string $contentType = self::contentTypes['apiV1TeamNotificationsChannelsPost'][0])
    {
        $returnType = '\emailguardSdk\Model\GetNotificationChannelResponse';
        $request = $this->apiV1TeamNotificationsChannelsPostRequest($create_notification_channel_input, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1TeamNotificationsChannelsPost'
     *
     * @param  \emailguardSdk\Model\CreateNotificationChannelInput $create_notification_channel_input Channel name, type, and type-specific configuration (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsChannelsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1TeamNotificationsChannelsPostRequest($create_notification_channel_input, string $contentType = self::contentTypes['apiV1TeamNotificationsChannelsPost'][0])
    {

        // verify the required parameter 'create_notification_channel_input' is set
        if ($create_notification_channel_input === null || (is_array($create_notification_channel_input) && count($create_notification_channel_input) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_notification_channel_input when calling apiV1TeamNotificationsChannelsPost'
            );
        }


        $resourcePath = '/api/v1/team/notifications/channels';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_notification_channel_input)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_notification_channel_input));
            } else {
                $httpBody = $create_notification_channel_input;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
