<?php
/**
 * InvitesApi
 * PHP version 8.1
 *
 * @category Class
 * @package  emailguardSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EmailGuard Public API
 *
 * Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dev@emailguard.co
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace emailguardSdk\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use emailguardSdk\ApiException;
use emailguardSdk\Configuration;
use emailguardSdk\FormDataProcessor;
use emailguardSdk\HeaderSelector;
use emailguardSdk\ObjectSerializer;

/**
 * InvitesApi Class Doc Comment
 *
 * @category Class
 * @package  emailguardSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InvitesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'apiV1TeamMembersInvitesGet' => [
            'application/json',
        ],
        'apiV1TeamMembersInvitesInviteIdDelete' => [
            'application/json',
        ],
        'apiV1TeamMembersInvitesPost' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation apiV1TeamMembersInvitesGet
     *
     * List pending team invites
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamMembersInvitesGet'] to see the possible values for this operation
     *
     * @throws \emailguardSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \emailguardSdk\Model\ListPublicTeamInvitesResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse
     */
    public function apiV1TeamMembersInvitesGet(string $contentType = self::contentTypes['apiV1TeamMembersInvitesGet'][0])
    {
        list($response) = $this->apiV1TeamMembersInvitesGetWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation apiV1TeamMembersInvitesGetWithHttpInfo
     *
     * List pending team invites
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamMembersInvitesGet'] to see the possible values for this operation
     *
     * @throws \emailguardSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \emailguardSdk\Model\ListPublicTeamInvitesResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1TeamMembersInvitesGetWithHttpInfo(string $contentType = self::contentTypes['apiV1TeamMembersInvitesGet'][0])
    {
        $request = $this->apiV1TeamMembersInvitesGetRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\ListPublicTeamInvitesResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\emailguardSdk\Model\ListPublicTeamInvitesResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\ListPublicTeamInvitesResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV1TeamMembersInvitesGetAsync
     *
     * List pending team invites
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamMembersInvitesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1TeamMembersInvitesGetAsync(string $contentType = self::contentTypes['apiV1TeamMembersInvitesGet'][0])
    {
        return $this->apiV1TeamMembersInvitesGetAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1TeamMembersInvitesGetAsyncWithHttpInfo
     *
     * List pending team invites
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamMembersInvitesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1TeamMembersInvitesGetAsyncWithHttpInfo(string $contentType = self::contentTypes['apiV1TeamMembersInvitesGet'][0])
    {
        $returnType = '\emailguardSdk\Model\ListPublicTeamInvitesResponse';
        $request = $this->apiV1TeamMembersInvitesGetRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1TeamMembersInvitesGet'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamMembersInvitesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1TeamMembersInvitesGetRequest(string $contentType = self::contentTypes['apiV1TeamMembersInvitesGet'][0])
    {


        $resourcePath = '/api/v1/team/members/invites';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1TeamMembersInvitesInviteIdDelete
     *
     * Cancel a pending invite
     *
     * @param  string $invite_id UUID of the pending invite to cancel (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamMembersInvitesInviteIdDelete'] to see the possible values for this operation
     *
     * @throws \emailguardSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \emailguardSdk\Model\MessageResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse
     */
    public function apiV1TeamMembersInvitesInviteIdDelete($invite_id, string $contentType = self::contentTypes['apiV1TeamMembersInvitesInviteIdDelete'][0])
    {
        list($response) = $this->apiV1TeamMembersInvitesInviteIdDeleteWithHttpInfo($invite_id, $contentType);
        return $response;
    }

    /**
     * Operation apiV1TeamMembersInvitesInviteIdDeleteWithHttpInfo
     *
     * Cancel a pending invite
     *
     * @param  string $invite_id UUID of the pending invite to cancel (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamMembersInvitesInviteIdDelete'] to see the possible values for this operation
     *
     * @throws \emailguardSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \emailguardSdk\Model\MessageResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1TeamMembersInvitesInviteIdDeleteWithHttpInfo($invite_id, string $contentType = self::contentTypes['apiV1TeamMembersInvitesInviteIdDelete'][0])
    {
        $request = $this->apiV1TeamMembersInvitesInviteIdDeleteRequest($invite_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\MessageResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\emailguardSdk\Model\MessageResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\MessageResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV1TeamMembersInvitesInviteIdDeleteAsync
     *
     * Cancel a pending invite
     *
     * @param  string $invite_id UUID of the pending invite to cancel (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamMembersInvitesInviteIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1TeamMembersInvitesInviteIdDeleteAsync($invite_id, string $contentType = self::contentTypes['apiV1TeamMembersInvitesInviteIdDelete'][0])
    {
        return $this->apiV1TeamMembersInvitesInviteIdDeleteAsyncWithHttpInfo($invite_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1TeamMembersInvitesInviteIdDeleteAsyncWithHttpInfo
     *
     * Cancel a pending invite
     *
     * @param  string $invite_id UUID of the pending invite to cancel (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamMembersInvitesInviteIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1TeamMembersInvitesInviteIdDeleteAsyncWithHttpInfo($invite_id, string $contentType = self::contentTypes['apiV1TeamMembersInvitesInviteIdDelete'][0])
    {
        $returnType = '\emailguardSdk\Model\MessageResponse';
        $request = $this->apiV1TeamMembersInvitesInviteIdDeleteRequest($invite_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1TeamMembersInvitesInviteIdDelete'
     *
     * @param  string $invite_id UUID of the pending invite to cancel (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamMembersInvitesInviteIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1TeamMembersInvitesInviteIdDeleteRequest($invite_id, string $contentType = self::contentTypes['apiV1TeamMembersInvitesInviteIdDelete'][0])
    {

        // verify the required parameter 'invite_id' is set
        if ($invite_id === null || (is_array($invite_id) && count($invite_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $invite_id when calling apiV1TeamMembersInvitesInviteIdDelete'
            );
        }


        $resourcePath = '/api/v1/team/members/invites/{inviteId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($invite_id !== null) {
            $resourcePath = str_replace(
                '{inviteId}',
                ObjectSerializer::toPathValue($invite_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1TeamMembersInvitesPost
     *
     * Invite a team member
     *
     * @param  \emailguardSdk\Model\InviteTeamMemberInput $invite_team_member_input Invitee email and role to assign on acceptance (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamMembersInvitesPost'] to see the possible values for this operation
     *
     * @throws \emailguardSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \emailguardSdk\Model\MessageResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse
     */
    public function apiV1TeamMembersInvitesPost($invite_team_member_input, string $contentType = self::contentTypes['apiV1TeamMembersInvitesPost'][0])
    {
        list($response) = $this->apiV1TeamMembersInvitesPostWithHttpInfo($invite_team_member_input, $contentType);
        return $response;
    }

    /**
     * Operation apiV1TeamMembersInvitesPostWithHttpInfo
     *
     * Invite a team member
     *
     * @param  \emailguardSdk\Model\InviteTeamMemberInput $invite_team_member_input Invitee email and role to assign on acceptance (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamMembersInvitesPost'] to see the possible values for this operation
     *
     * @throws \emailguardSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \emailguardSdk\Model\MessageResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1TeamMembersInvitesPostWithHttpInfo($invite_team_member_input, string $contentType = self::contentTypes['apiV1TeamMembersInvitesPost'][0])
    {
        $request = $this->apiV1TeamMembersInvitesPostRequest($invite_team_member_input, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\MessageResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\emailguardSdk\Model\MessageResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\MessageResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV1TeamMembersInvitesPostAsync
     *
     * Invite a team member
     *
     * @param  \emailguardSdk\Model\InviteTeamMemberInput $invite_team_member_input Invitee email and role to assign on acceptance (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamMembersInvitesPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1TeamMembersInvitesPostAsync($invite_team_member_input, string $contentType = self::contentTypes['apiV1TeamMembersInvitesPost'][0])
    {
        return $this->apiV1TeamMembersInvitesPostAsyncWithHttpInfo($invite_team_member_input, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1TeamMembersInvitesPostAsyncWithHttpInfo
     *
     * Invite a team member
     *
     * @param  \emailguardSdk\Model\InviteTeamMemberInput $invite_team_member_input Invitee email and role to assign on acceptance (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamMembersInvitesPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1TeamMembersInvitesPostAsyncWithHttpInfo($invite_team_member_input, string $contentType = self::contentTypes['apiV1TeamMembersInvitesPost'][0])
    {
        $returnType = '\emailguardSdk\Model\MessageResponse';
        $request = $this->apiV1TeamMembersInvitesPostRequest($invite_team_member_input, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1TeamMembersInvitesPost'
     *
     * @param  \emailguardSdk\Model\InviteTeamMemberInput $invite_team_member_input Invitee email and role to assign on acceptance (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamMembersInvitesPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1TeamMembersInvitesPostRequest($invite_team_member_input, string $contentType = self::contentTypes['apiV1TeamMembersInvitesPost'][0])
    {

        // verify the required parameter 'invite_team_member_input' is set
        if ($invite_team_member_input === null || (is_array($invite_team_member_input) && count($invite_team_member_input) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $invite_team_member_input when calling apiV1TeamMembersInvitesPost'
            );
        }


        $resourcePath = '/api/v1/team/members/invites';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($invite_team_member_input)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($invite_team_member_input));
            } else {
                $httpBody = $invite_team_member_input;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
