<?php
/**
 * RulesApi
 * PHP version 8.1
 *
 * @category Class
 * @package  emailguardSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EmailGuard Public API
 *
 * Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dev@emailguard.co
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace emailguardSdk\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use emailguardSdk\ApiException;
use emailguardSdk\Configuration;
use emailguardSdk\FormDataProcessor;
use emailguardSdk\HeaderSelector;
use emailguardSdk\ObjectSerializer;

/**
 * RulesApi Class Doc Comment
 *
 * @category Class
 * @package  emailguardSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RulesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'apiV1TeamNotificationsRulesGet' => [
            'application/json',
        ],
        'apiV1TeamNotificationsRulesPost' => [
            'application/json',
        ],
        'apiV1TeamNotificationsRulesRuleIdDelete' => [
            'application/json',
        ],
        'apiV1TeamNotificationsRulesRuleIdPut' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation apiV1TeamNotificationsRulesGet
     *
     * List notification rules
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsRulesGet'] to see the possible values for this operation
     *
     * @throws \emailguardSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \emailguardSdk\Model\GetNotificationRulesResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse
     */
    public function apiV1TeamNotificationsRulesGet(string $contentType = self::contentTypes['apiV1TeamNotificationsRulesGet'][0])
    {
        list($response) = $this->apiV1TeamNotificationsRulesGetWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation apiV1TeamNotificationsRulesGetWithHttpInfo
     *
     * List notification rules
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsRulesGet'] to see the possible values for this operation
     *
     * @throws \emailguardSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \emailguardSdk\Model\GetNotificationRulesResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1TeamNotificationsRulesGetWithHttpInfo(string $contentType = self::contentTypes['apiV1TeamNotificationsRulesGet'][0])
    {
        $request = $this->apiV1TeamNotificationsRulesGetRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\GetNotificationRulesResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\emailguardSdk\Model\GetNotificationRulesResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\GetNotificationRulesResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV1TeamNotificationsRulesGetAsync
     *
     * List notification rules
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsRulesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1TeamNotificationsRulesGetAsync(string $contentType = self::contentTypes['apiV1TeamNotificationsRulesGet'][0])
    {
        return $this->apiV1TeamNotificationsRulesGetAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1TeamNotificationsRulesGetAsyncWithHttpInfo
     *
     * List notification rules
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsRulesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1TeamNotificationsRulesGetAsyncWithHttpInfo(string $contentType = self::contentTypes['apiV1TeamNotificationsRulesGet'][0])
    {
        $returnType = '\emailguardSdk\Model\GetNotificationRulesResponse';
        $request = $this->apiV1TeamNotificationsRulesGetRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1TeamNotificationsRulesGet'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsRulesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1TeamNotificationsRulesGetRequest(string $contentType = self::contentTypes['apiV1TeamNotificationsRulesGet'][0])
    {


        $resourcePath = '/api/v1/team/notifications/rules';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1TeamNotificationsRulesPost
     *
     * Create notification rule
     *
     * @param  \emailguardSdk\Model\CreateNotificationRuleInput $create_notification_rule_input Rule name, event types, and channel targets (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsRulesPost'] to see the possible values for this operation
     *
     * @throws \emailguardSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \emailguardSdk\Model\IdDataResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse
     */
    public function apiV1TeamNotificationsRulesPost($create_notification_rule_input, string $contentType = self::contentTypes['apiV1TeamNotificationsRulesPost'][0])
    {
        list($response) = $this->apiV1TeamNotificationsRulesPostWithHttpInfo($create_notification_rule_input, $contentType);
        return $response;
    }

    /**
     * Operation apiV1TeamNotificationsRulesPostWithHttpInfo
     *
     * Create notification rule
     *
     * @param  \emailguardSdk\Model\CreateNotificationRuleInput $create_notification_rule_input Rule name, event types, and channel targets (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsRulesPost'] to see the possible values for this operation
     *
     * @throws \emailguardSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \emailguardSdk\Model\IdDataResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1TeamNotificationsRulesPostWithHttpInfo($create_notification_rule_input, string $contentType = self::contentTypes['apiV1TeamNotificationsRulesPost'][0])
    {
        $request = $this->apiV1TeamNotificationsRulesPostRequest($create_notification_rule_input, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\IdDataResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\emailguardSdk\Model\IdDataResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\IdDataResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV1TeamNotificationsRulesPostAsync
     *
     * Create notification rule
     *
     * @param  \emailguardSdk\Model\CreateNotificationRuleInput $create_notification_rule_input Rule name, event types, and channel targets (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsRulesPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1TeamNotificationsRulesPostAsync($create_notification_rule_input, string $contentType = self::contentTypes['apiV1TeamNotificationsRulesPost'][0])
    {
        return $this->apiV1TeamNotificationsRulesPostAsyncWithHttpInfo($create_notification_rule_input, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1TeamNotificationsRulesPostAsyncWithHttpInfo
     *
     * Create notification rule
     *
     * @param  \emailguardSdk\Model\CreateNotificationRuleInput $create_notification_rule_input Rule name, event types, and channel targets (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsRulesPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1TeamNotificationsRulesPostAsyncWithHttpInfo($create_notification_rule_input, string $contentType = self::contentTypes['apiV1TeamNotificationsRulesPost'][0])
    {
        $returnType = '\emailguardSdk\Model\IdDataResponse';
        $request = $this->apiV1TeamNotificationsRulesPostRequest($create_notification_rule_input, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1TeamNotificationsRulesPost'
     *
     * @param  \emailguardSdk\Model\CreateNotificationRuleInput $create_notification_rule_input Rule name, event types, and channel targets (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsRulesPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1TeamNotificationsRulesPostRequest($create_notification_rule_input, string $contentType = self::contentTypes['apiV1TeamNotificationsRulesPost'][0])
    {

        // verify the required parameter 'create_notification_rule_input' is set
        if ($create_notification_rule_input === null || (is_array($create_notification_rule_input) && count($create_notification_rule_input) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_notification_rule_input when calling apiV1TeamNotificationsRulesPost'
            );
        }


        $resourcePath = '/api/v1/team/notifications/rules';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_notification_rule_input)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_notification_rule_input));
            } else {
                $httpBody = $create_notification_rule_input;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1TeamNotificationsRulesRuleIdDelete
     *
     * Delete notification rule
     *
     * @param  string $rule_id UUID of the notification rule to delete (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsRulesRuleIdDelete'] to see the possible values for this operation
     *
     * @throws \emailguardSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \emailguardSdk\Model\MessageResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse
     */
    public function apiV1TeamNotificationsRulesRuleIdDelete($rule_id, string $contentType = self::contentTypes['apiV1TeamNotificationsRulesRuleIdDelete'][0])
    {
        list($response) = $this->apiV1TeamNotificationsRulesRuleIdDeleteWithHttpInfo($rule_id, $contentType);
        return $response;
    }

    /**
     * Operation apiV1TeamNotificationsRulesRuleIdDeleteWithHttpInfo
     *
     * Delete notification rule
     *
     * @param  string $rule_id UUID of the notification rule to delete (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsRulesRuleIdDelete'] to see the possible values for this operation
     *
     * @throws \emailguardSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \emailguardSdk\Model\MessageResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1TeamNotificationsRulesRuleIdDeleteWithHttpInfo($rule_id, string $contentType = self::contentTypes['apiV1TeamNotificationsRulesRuleIdDelete'][0])
    {
        $request = $this->apiV1TeamNotificationsRulesRuleIdDeleteRequest($rule_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\MessageResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\emailguardSdk\Model\MessageResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\MessageResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV1TeamNotificationsRulesRuleIdDeleteAsync
     *
     * Delete notification rule
     *
     * @param  string $rule_id UUID of the notification rule to delete (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsRulesRuleIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1TeamNotificationsRulesRuleIdDeleteAsync($rule_id, string $contentType = self::contentTypes['apiV1TeamNotificationsRulesRuleIdDelete'][0])
    {
        return $this->apiV1TeamNotificationsRulesRuleIdDeleteAsyncWithHttpInfo($rule_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1TeamNotificationsRulesRuleIdDeleteAsyncWithHttpInfo
     *
     * Delete notification rule
     *
     * @param  string $rule_id UUID of the notification rule to delete (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsRulesRuleIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1TeamNotificationsRulesRuleIdDeleteAsyncWithHttpInfo($rule_id, string $contentType = self::contentTypes['apiV1TeamNotificationsRulesRuleIdDelete'][0])
    {
        $returnType = '\emailguardSdk\Model\MessageResponse';
        $request = $this->apiV1TeamNotificationsRulesRuleIdDeleteRequest($rule_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1TeamNotificationsRulesRuleIdDelete'
     *
     * @param  string $rule_id UUID of the notification rule to delete (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsRulesRuleIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1TeamNotificationsRulesRuleIdDeleteRequest($rule_id, string $contentType = self::contentTypes['apiV1TeamNotificationsRulesRuleIdDelete'][0])
    {

        // verify the required parameter 'rule_id' is set
        if ($rule_id === null || (is_array($rule_id) && count($rule_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $rule_id when calling apiV1TeamNotificationsRulesRuleIdDelete'
            );
        }


        $resourcePath = '/api/v1/team/notifications/rules/{ruleId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($rule_id !== null) {
            $resourcePath = str_replace(
                '{ruleId}',
                ObjectSerializer::toPathValue($rule_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1TeamNotificationsRulesRuleIdPut
     *
     * Update notification rule
     *
     * @param  string $rule_id UUID of the notification rule to update (required)
     * @param  \emailguardSdk\Model\UpdateNotificationRuleInput $update_notification_rule_input Fields to update on the rule (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsRulesRuleIdPut'] to see the possible values for this operation
     *
     * @throws \emailguardSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \emailguardSdk\Model\MessageResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse
     */
    public function apiV1TeamNotificationsRulesRuleIdPut($rule_id, $update_notification_rule_input, string $contentType = self::contentTypes['apiV1TeamNotificationsRulesRuleIdPut'][0])
    {
        list($response) = $this->apiV1TeamNotificationsRulesRuleIdPutWithHttpInfo($rule_id, $update_notification_rule_input, $contentType);
        return $response;
    }

    /**
     * Operation apiV1TeamNotificationsRulesRuleIdPutWithHttpInfo
     *
     * Update notification rule
     *
     * @param  string $rule_id UUID of the notification rule to update (required)
     * @param  \emailguardSdk\Model\UpdateNotificationRuleInput $update_notification_rule_input Fields to update on the rule (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsRulesRuleIdPut'] to see the possible values for this operation
     *
     * @throws \emailguardSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \emailguardSdk\Model\MessageResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse|\emailguardSdk\Model\BaseResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1TeamNotificationsRulesRuleIdPutWithHttpInfo($rule_id, $update_notification_rule_input, string $contentType = self::contentTypes['apiV1TeamNotificationsRulesRuleIdPut'][0])
    {
        $request = $this->apiV1TeamNotificationsRulesRuleIdPutRequest($rule_id, $update_notification_rule_input, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\MessageResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\emailguardSdk\Model\BaseResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\emailguardSdk\Model\MessageResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\MessageResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\emailguardSdk\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV1TeamNotificationsRulesRuleIdPutAsync
     *
     * Update notification rule
     *
     * @param  string $rule_id UUID of the notification rule to update (required)
     * @param  \emailguardSdk\Model\UpdateNotificationRuleInput $update_notification_rule_input Fields to update on the rule (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsRulesRuleIdPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1TeamNotificationsRulesRuleIdPutAsync($rule_id, $update_notification_rule_input, string $contentType = self::contentTypes['apiV1TeamNotificationsRulesRuleIdPut'][0])
    {
        return $this->apiV1TeamNotificationsRulesRuleIdPutAsyncWithHttpInfo($rule_id, $update_notification_rule_input, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1TeamNotificationsRulesRuleIdPutAsyncWithHttpInfo
     *
     * Update notification rule
     *
     * @param  string $rule_id UUID of the notification rule to update (required)
     * @param  \emailguardSdk\Model\UpdateNotificationRuleInput $update_notification_rule_input Fields to update on the rule (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsRulesRuleIdPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1TeamNotificationsRulesRuleIdPutAsyncWithHttpInfo($rule_id, $update_notification_rule_input, string $contentType = self::contentTypes['apiV1TeamNotificationsRulesRuleIdPut'][0])
    {
        $returnType = '\emailguardSdk\Model\MessageResponse';
        $request = $this->apiV1TeamNotificationsRulesRuleIdPutRequest($rule_id, $update_notification_rule_input, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1TeamNotificationsRulesRuleIdPut'
     *
     * @param  string $rule_id UUID of the notification rule to update (required)
     * @param  \emailguardSdk\Model\UpdateNotificationRuleInput $update_notification_rule_input Fields to update on the rule (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1TeamNotificationsRulesRuleIdPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1TeamNotificationsRulesRuleIdPutRequest($rule_id, $update_notification_rule_input, string $contentType = self::contentTypes['apiV1TeamNotificationsRulesRuleIdPut'][0])
    {

        // verify the required parameter 'rule_id' is set
        if ($rule_id === null || (is_array($rule_id) && count($rule_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $rule_id when calling apiV1TeamNotificationsRulesRuleIdPut'
            );
        }

        // verify the required parameter 'update_notification_rule_input' is set
        if ($update_notification_rule_input === null || (is_array($update_notification_rule_input) && count($update_notification_rule_input) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $update_notification_rule_input when calling apiV1TeamNotificationsRulesRuleIdPut'
            );
        }


        $resourcePath = '/api/v1/team/notifications/rules/{ruleId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($rule_id !== null) {
            $resourcePath = str_replace(
                '{ruleId}',
                ObjectSerializer::toPathValue($rule_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($update_notification_rule_input)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($update_notification_rule_input));
            } else {
                $httpBody = $update_notification_rule_input;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
