<?php
/**
 * EmailDetectData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  emailguardSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EmailGuard Public API
 *
 * Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dev@emailguard.co
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace emailguardSdk\Model;

use \ArrayAccess;
use \emailguardSdk\ObjectSerializer;

/**
 * EmailDetectData Class Doc Comment
 *
 * @category Class
 * @package  emailguardSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EmailDetectData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'EmailDetectData';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'detection_source' => 'string',
        'disposable' => 'bool',
        'disposable_provider' => 'string',
        'domain' => 'string',
        'email' => 'string',
        'normalized' => 'string',
        'public_domain' => 'bool',
        'relay_domain' => 'bool',
        'relay_provider' => 'string',
        'role_address' => 'bool',
        'subaddressing' => 'bool',
        'suggested_domain' => 'string',
        'suggested_email' => 'string',
        'syntax_validation' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'detection_source' => null,
        'disposable' => null,
        'disposable_provider' => null,
        'domain' => null,
        'email' => null,
        'normalized' => null,
        'public_domain' => null,
        'relay_domain' => null,
        'relay_provider' => null,
        'role_address' => null,
        'subaddressing' => null,
        'suggested_domain' => null,
        'suggested_email' => null,
        'syntax_validation' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'detection_source' => false,
        'disposable' => false,
        'disposable_provider' => false,
        'domain' => false,
        'email' => false,
        'normalized' => false,
        'public_domain' => false,
        'relay_domain' => false,
        'relay_provider' => false,
        'role_address' => false,
        'subaddressing' => false,
        'suggested_domain' => false,
        'suggested_email' => false,
        'syntax_validation' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'detection_source' => 'detection_source',
        'disposable' => 'disposable',
        'disposable_provider' => 'disposable_provider',
        'domain' => 'domain',
        'email' => 'email',
        'normalized' => 'normalized',
        'public_domain' => 'public_domain',
        'relay_domain' => 'relay_domain',
        'relay_provider' => 'relay_provider',
        'role_address' => 'role_address',
        'subaddressing' => 'subaddressing',
        'suggested_domain' => 'suggested_domain',
        'suggested_email' => 'suggested_email',
        'syntax_validation' => 'syntax_validation'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'detection_source' => 'setDetectionSource',
        'disposable' => 'setDisposable',
        'disposable_provider' => 'setDisposableProvider',
        'domain' => 'setDomain',
        'email' => 'setEmail',
        'normalized' => 'setNormalized',
        'public_domain' => 'setPublicDomain',
        'relay_domain' => 'setRelayDomain',
        'relay_provider' => 'setRelayProvider',
        'role_address' => 'setRoleAddress',
        'subaddressing' => 'setSubaddressing',
        'suggested_domain' => 'setSuggestedDomain',
        'suggested_email' => 'setSuggestedEmail',
        'syntax_validation' => 'setSyntaxValidation'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'detection_source' => 'getDetectionSource',
        'disposable' => 'getDisposable',
        'disposable_provider' => 'getDisposableProvider',
        'domain' => 'getDomain',
        'email' => 'getEmail',
        'normalized' => 'getNormalized',
        'public_domain' => 'getPublicDomain',
        'relay_domain' => 'getRelayDomain',
        'relay_provider' => 'getRelayProvider',
        'role_address' => 'getRoleAddress',
        'subaddressing' => 'getSubaddressing',
        'suggested_domain' => 'getSuggestedDomain',
        'suggested_email' => 'getSuggestedEmail',
        'syntax_validation' => 'getSyntaxValidation'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('detection_source', $data ?? [], null);
        $this->setIfExists('disposable', $data ?? [], null);
        $this->setIfExists('disposable_provider', $data ?? [], null);
        $this->setIfExists('domain', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('normalized', $data ?? [], null);
        $this->setIfExists('public_domain', $data ?? [], null);
        $this->setIfExists('relay_domain', $data ?? [], null);
        $this->setIfExists('relay_provider', $data ?? [], null);
        $this->setIfExists('role_address', $data ?? [], null);
        $this->setIfExists('subaddressing', $data ?? [], null);
        $this->setIfExists('suggested_domain', $data ?? [], null);
        $this->setIfExists('suggested_email', $data ?? [], null);
        $this->setIfExists('syntax_validation', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets detection_source
     *
     * @return string|null
     */
    public function getDetectionSource()
    {
        return $this->container['detection_source'];
    }

    /**
     * Sets detection_source
     *
     * @param string|null $detection_source detection_source
     *
     * @return self
     */
    public function setDetectionSource($detection_source)
    {
        if (is_null($detection_source)) {
            throw new \InvalidArgumentException('non-nullable detection_source cannot be null');
        }
        $this->container['detection_source'] = $detection_source;

        return $this;
    }

    /**
     * Gets disposable
     *
     * @return bool|null
     */
    public function getDisposable()
    {
        return $this->container['disposable'];
    }

    /**
     * Sets disposable
     *
     * @param bool|null $disposable disposable
     *
     * @return self
     */
    public function setDisposable($disposable)
    {
        if (is_null($disposable)) {
            throw new \InvalidArgumentException('non-nullable disposable cannot be null');
        }
        $this->container['disposable'] = $disposable;

        return $this;
    }

    /**
     * Gets disposable_provider
     *
     * @return string|null
     */
    public function getDisposableProvider()
    {
        return $this->container['disposable_provider'];
    }

    /**
     * Sets disposable_provider
     *
     * @param string|null $disposable_provider disposable_provider
     *
     * @return self
     */
    public function setDisposableProvider($disposable_provider)
    {
        if (is_null($disposable_provider)) {
            throw new \InvalidArgumentException('non-nullable disposable_provider cannot be null');
        }
        $this->container['disposable_provider'] = $disposable_provider;

        return $this;
    }

    /**
     * Gets domain
     *
     * @return string|null
     */
    public function getDomain()
    {
        return $this->container['domain'];
    }

    /**
     * Sets domain
     *
     * @param string|null $domain domain
     *
     * @return self
     */
    public function setDomain($domain)
    {
        if (is_null($domain)) {
            throw new \InvalidArgumentException('non-nullable domain cannot be null');
        }
        $this->container['domain'] = $domain;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email email
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            throw new \InvalidArgumentException('non-nullable email cannot be null');
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets normalized
     *
     * @return string|null
     */
    public function getNormalized()
    {
        return $this->container['normalized'];
    }

    /**
     * Sets normalized
     *
     * @param string|null $normalized normalized
     *
     * @return self
     */
    public function setNormalized($normalized)
    {
        if (is_null($normalized)) {
            throw new \InvalidArgumentException('non-nullable normalized cannot be null');
        }
        $this->container['normalized'] = $normalized;

        return $this;
    }

    /**
     * Gets public_domain
     *
     * @return bool|null
     */
    public function getPublicDomain()
    {
        return $this->container['public_domain'];
    }

    /**
     * Sets public_domain
     *
     * @param bool|null $public_domain public_domain
     *
     * @return self
     */
    public function setPublicDomain($public_domain)
    {
        if (is_null($public_domain)) {
            throw new \InvalidArgumentException('non-nullable public_domain cannot be null');
        }
        $this->container['public_domain'] = $public_domain;

        return $this;
    }

    /**
     * Gets relay_domain
     *
     * @return bool|null
     */
    public function getRelayDomain()
    {
        return $this->container['relay_domain'];
    }

    /**
     * Sets relay_domain
     *
     * @param bool|null $relay_domain relay_domain
     *
     * @return self
     */
    public function setRelayDomain($relay_domain)
    {
        if (is_null($relay_domain)) {
            throw new \InvalidArgumentException('non-nullable relay_domain cannot be null');
        }
        $this->container['relay_domain'] = $relay_domain;

        return $this;
    }

    /**
     * Gets relay_provider
     *
     * @return string|null
     */
    public function getRelayProvider()
    {
        return $this->container['relay_provider'];
    }

    /**
     * Sets relay_provider
     *
     * @param string|null $relay_provider relay_provider
     *
     * @return self
     */
    public function setRelayProvider($relay_provider)
    {
        if (is_null($relay_provider)) {
            throw new \InvalidArgumentException('non-nullable relay_provider cannot be null');
        }
        $this->container['relay_provider'] = $relay_provider;

        return $this;
    }

    /**
     * Gets role_address
     *
     * @return bool|null
     */
    public function getRoleAddress()
    {
        return $this->container['role_address'];
    }

    /**
     * Sets role_address
     *
     * @param bool|null $role_address role_address
     *
     * @return self
     */
    public function setRoleAddress($role_address)
    {
        if (is_null($role_address)) {
            throw new \InvalidArgumentException('non-nullable role_address cannot be null');
        }
        $this->container['role_address'] = $role_address;

        return $this;
    }

    /**
     * Gets subaddressing
     *
     * @return bool|null
     */
    public function getSubaddressing()
    {
        return $this->container['subaddressing'];
    }

    /**
     * Sets subaddressing
     *
     * @param bool|null $subaddressing subaddressing
     *
     * @return self
     */
    public function setSubaddressing($subaddressing)
    {
        if (is_null($subaddressing)) {
            throw new \InvalidArgumentException('non-nullable subaddressing cannot be null');
        }
        $this->container['subaddressing'] = $subaddressing;

        return $this;
    }

    /**
     * Gets suggested_domain
     *
     * @return string|null
     */
    public function getSuggestedDomain()
    {
        return $this->container['suggested_domain'];
    }

    /**
     * Sets suggested_domain
     *
     * @param string|null $suggested_domain Corrected domain candidate when a domain or TLD typo rule matches.
     *
     * @return self
     */
    public function setSuggestedDomain($suggested_domain)
    {
        if (is_null($suggested_domain)) {
            throw new \InvalidArgumentException('non-nullable suggested_domain cannot be null');
        }
        $this->container['suggested_domain'] = $suggested_domain;

        return $this;
    }

    /**
     * Gets suggested_email
     *
     * @return string|null
     */
    public function getSuggestedEmail()
    {
        return $this->container['suggested_email'];
    }

    /**
     * Sets suggested_email
     *
     * @param string|null $suggested_email Corrected email candidate when a domain or TLD typo rule matches.
     *
     * @return self
     */
    public function setSuggestedEmail($suggested_email)
    {
        if (is_null($suggested_email)) {
            throw new \InvalidArgumentException('non-nullable suggested_email cannot be null');
        }
        $this->container['suggested_email'] = $suggested_email;

        return $this;
    }

    /**
     * Gets syntax_validation
     *
     * @return bool|null
     */
    public function getSyntaxValidation()
    {
        return $this->container['syntax_validation'];
    }

    /**
     * Sets syntax_validation
     *
     * @param bool|null $syntax_validation syntax_validation
     *
     * @return self
     */
    public function setSyntaxValidation($syntax_validation)
    {
        if (is_null($syntax_validation)) {
            throw new \InvalidArgumentException('non-nullable syntax_validation cannot be null');
        }
        $this->container['syntax_validation'] = $syntax_validation;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


