<?php
/**
 * EmailDetectDataTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  emailguardSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EmailGuard Public API
 *
 * Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dev@emailguard.co
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace emailguardSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * EmailDetectDataTest Class Doc Comment
 *
 * @category    Class
 * @description EmailDetectData
 * @package     emailguardSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EmailDetectDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "EmailDetectData"
     */
    public function testEmailDetectData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "detection_source"
     */
    public function testPropertyDetectionSource()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "disposable"
     */
    public function testPropertyDisposable()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "disposable_provider"
     */
    public function testPropertyDisposableProvider()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "domain"
     */
    public function testPropertyDomain()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "normalized"
     */
    public function testPropertyNormalized()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "public_domain"
     */
    public function testPropertyPublicDomain()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "relay_domain"
     */
    public function testPropertyRelayDomain()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "relay_provider"
     */
    public function testPropertyRelayProvider()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "role_address"
     */
    public function testPropertyRoleAddress()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "subaddressing"
     */
    public function testPropertySubaddressing()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "suggested_domain"
     */
    public function testPropertySuggestedDomain()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "suggested_email"
     */
    public function testPropertySuggestedEmail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "syntax_validation"
     */
    public function testPropertySyntaxValidation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
