<?php
/**
 * UpdateNotificationChannelInputTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  emailguardSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EmailGuard Public API
 *
 * Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dev@emailguard.co
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace emailguardSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * UpdateNotificationChannelInputTest Class Doc Comment
 *
 * @category    Class
 * @description UpdateNotificationChannelInput
 * @package     emailguardSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UpdateNotificationChannelInputTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UpdateNotificationChannelInput"
     */
    public function testUpdateNotificationChannelInput()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "config"
     */
    public function testPropertyConfig()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
