<?php
/**
 * ChannelsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  emailguardSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EmailGuard Public API
 *
 * Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dev@emailguard.co
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace emailguardSdk\Test\Api;

use \emailguardSdk\Configuration;
use \emailguardSdk\ApiException;
use \emailguardSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ChannelsApiTest Class Doc Comment
 *
 * @category Class
 * @package  emailguardSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ChannelsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV1TeamNotificationsChannelsChannelIdDelete
     *
     * Delete notification channel.
     *
     */
    public function testApiV1TeamNotificationsChannelsChannelIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1TeamNotificationsChannelsChannelIdPut
     *
     * Update notification channel.
     *
     */
    public function testApiV1TeamNotificationsChannelsChannelIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1TeamNotificationsChannelsChannelIdTestPost
     *
     * Test notification channel.
     *
     */
    public function testApiV1TeamNotificationsChannelsChannelIdTestPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1TeamNotificationsChannelsGet
     *
     * List notification channels.
     *
     */
    public function testApiV1TeamNotificationsChannelsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1TeamNotificationsChannelsPost
     *
     * Create notification channel.
     *
     */
    public function testApiV1TeamNotificationsChannelsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
